# Generated by Django 4.2.6 on 2023-10-23 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mypost",
            name="photo",
        ),
    ]
